services:
  wallet-db:
    image: postgres:17.5-alpine
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_DB: db_wallet_app
      POSTGRES_USER: db_wallet_app
      POSTGRES_PASSWORD: db_wallet_app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/:ro
  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    environment:
      APP_PORT: 8080
      PG_HOST: wallet-db
      PG_PORT: 5432
      PG_DB: db_wallet_app
      PG_USER: db_wallet_app
      PG_PASS: db_wallet_app
      PG_SSL: disable
    ports:
      - "8080:8080"
    depends_on:
      - wallet-db
      
volumes:
  pg_data:
    driver: local